version: "3.7"

# Chrome Browserless debugger: http://localhost:3000/#
# OrientDB GUI: http://localhost:2480/studio/index.html


services:

  testar:
    build: ./testar
  
  orient:
    image: orientdb
    expose:
      - 2424
    ports:
      - 2480:2480
    environment: 
      - ORIENTDB_ROOT_PASSWORD=root12345

  webdriver:
    image: browserless/chrome
    ports:
      - 3000:3000

