apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome-testar
  labels:
    app: selenium-node-chrome-testar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-node-chrome-testar
  template:
    metadata:
      labels:
        app: selenium-node-chrome-testar
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: selenium-node-chrome-testar
        image: aslomp/testar
        ports:
          - containerPort: 5555
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: HUB_HOST
            value: "selenium-hub"
          - name: HUB_PORT
            value: "4444"
          - name: testurl
            value: #{TestUrl}#
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
